config/routes.rb
Collaborave::Application.routes.draw do
  resources :projects, defaults: {format: :json} do
    resources :versions, only: [:index]
    resources :notes
    resources :collabs
    resources :tracks, only: [:index]
  end


  resources :versions, except: [:index] do
    resources :track_diffs, only: [:index]
  end

  resources :track_diffs, except: [:index] do 
    resources :filters, only: [:index]
    resources :region_diffs, only: [:index]
  end

  resources :region_diffs, except: [:index] do
    resources :filters, only: [:index]
  end

  resources :tracks, except: [:index], defaults: {format: :json} do
    resources :regions, only: [:index]
    resources :filters, only: [:index]
  end

  resources :regions, except: [:index], defaults: {format: :json} do
    resources :filters, only: [:index]
  end

  resources :filters, except: [:index] do 
    resources :filter_automations, only: [:index]
  end 

  resources :filter_automations, except: [:index]
  

  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  root 'static_pages#home'
  match 'signup', to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/help', to: 'static_pages#help', via: 'get'
  match '/about', to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'
end

app/models/collab.rb
class Collab < ActiveRecord::Base
	belongs_to :collaborator, class_name: "User"
	belongs_to :project, class_name: "Project"
	validates :collaborator_id, presence: true
	validates :project_id, presence: true
end

app/models/filter.rb
class Filter < ActiveRecord::Base
	belongs_to :track
	belongs_to :track_diff
	belongs_to :region
	belongs_to :region_diff
	has_many :filter_automations, dependent: :destroy

end

app/models/filter_automation.rb
class FilterAutomation < ActiveRecord::Base
	belongs_to :filter
end

app/models/note.rb
class Note < ActiveRecord::Base
	belongs_to :project, class_name: "Project"
	belongs_to :collaborator, class_name: "User"
	default_scope -> { order('created_at ASC') }
	validates :collaborator_id, presence: true
	validates :project_id, presence: true
	validates :content, presence: true
end

app/models/project.rb
class Project < ActiveRecord::Base
	has_many :collabs, dependent: :destroy
	has_many :collaborators, through: :collabs, dependent: :destroy
	has_many :versions, dependent: :destroy
	has_many :tracks, dependent: :destroy
	has_many :notes, dependent: :destroy
	belongs_to :author, class_name: "User"
	default_scope -> { order('created_at DESC') }
	validates :author_id, presence: true
end

app/models/region.rb
class Region < ActiveRecord::Base
	mount_uploader :path, RegionUploader
  belongs_to :track
  has_many :filters, dependent: :destroy
  before_destroy :destroy_file

  def destroy_file
  	self.remove_path!
  end
end

app/models/region_diff.rb
class RegionDiff < ActiveRecord::Base
	has_many :filters
	belongs_to :track_diff
end

app/models/track.rb
class Track < ActiveRecord::Base
	belongs_to :project
	validates :name, presence: true
	has_many :regions, dependent: :destroy
	has_many :filters, dependent: :destroy

end

app/models/track_diff.rb
class TrackDiff < ActiveRecord::Base
	has_many :region_diffs
	has_many :filters
	belongs_to :version
end

app/models/user.rb
class User < ActiveRecord::Base
  
  has_many :projects, foreign_key: "author_id", dependent: :destroy
  has_many :collabs, foreign_key: "collaborator_id", dependent: :destroy
  has_many :reverse_collabs, foreign_key: "collaborator_id", class_name: "Collab", dependent: :destroy
  has_many :collab_projects, through: :reverse_collabs, source: :project, dependent: :destroy
  has_many :versions, foreign_key: "collaborator_id", dependent: :destroy
  has_many :notes, foreign_key: "collaborator_id"
  
  belongs_to :project, class_name: "Project"
  before_save { self.email = email.downcase }
  before_create :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  
  has_secure_password
  validates :password, length: { minimum: 6 }

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.encrypt(User.new_remember_token)
    end
end

app/models/version.rb
class Version < ActiveRecord::Base
	belongs_to :project, class_name: "Project"
	belongs_to :collaborator, class_name: "User"
	has_many :track_diffs, dependent: :destroy
	default_scope -> { order('created_at DESC') }
	validates :project_id, presence: true
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController


  def home 
    @region = Region.new
    @new_project = Project.new
    # if signed_in?
    #   @new_project  = current_user.projects.build(author_id: current_user)
    #   @user = current_user
    #   @projects = @user.projects.paginate(page: params[:page])
      
    # @collab_projects = @user.collab_projects.paginate(page: params[:page])
    # else
    #   @project = Project.find(1)
    #   @user = @project.author
    #   @version = Version.new
      
    #   @versions = @project.versions.paginate(page: params[:page])
    #   @track = @project.tracks.new
    #   @track.project_id = @project.id
    #   @tracks = @project.tracks.all
    #   @track_urls = []
    #   @track_names = []
    #   # @tracks.each  do |track| 
    #   #   @track_urls << track.path.url if track.path.url != nil
    #   #   @track_names << track.track_name if track.path.url != nil
    #   # end
    # end

  end

  def show
  end


  def help
  end

  def about
  end 

  def contact
  end
end

app/helpers/collabs_helper.rb
module CollabsHelper
end

app/helpers/filters_helper.rb
module FiltersHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/regions_helper.rb
module RegionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(user)
    remember_token = User.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    user.update_attribute(:remember_token, User.encrypt(remember_token))
    self.current_user = user
  end

  def signed_in?
  	!current_user.nil?
  end	

  def current_user=(user)
  	@current_user = user
  end
  
  def current_user
  	remember_token = User.encrypt(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
  end

  def current_user?(user)
    user == current_user
  end

  def signed_in_user
    unless signed_in?
      store_location
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
  	self.current_user = nil
  	cookies.delete(:remember_token)
  end			

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end
  
  def store_location
    session[:return_to] = request.url if request.get?
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar (http://gravatar.com/) for the given user.
  def gravatar_for(user, options = { size: 200 })
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    size = options[:size]
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/helpers/versions_helper.rb
module VersionsHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<div class="content-container">
	<h1>About Collaborave</h1>
	<p>Collaborave is a web app for music collaboration built on the latest web audio api. It gives you the ability to upload tracks and create mixes of your music to share with friends around the world. I realize that that it is missing a lot of important features: ability to make projects private, select collaborators, record and edit tracks, easy sharing to social media—not to mention a whole host of little bugs that need to be worked out. I'll be working on these over the coming months. Until then, feel free to use it as is.</p>
	</div>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Help') %>
<div class="content-container">
	<h1>Contact</h1>
	<p>I am too busy to take complaints for the next couple months. I realise this is missing all kinds of features. You'll have to live with it until I am done at the <a href="http://appacademy.io">App Academy</a> in February.</p>
	</div>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<div class="content-container">
	<h1>Help</h1>
	<p>Sign up to have access to projects. Once signed in, you can view other users' projects, make your own versions, or mixes, and create your own projects and upload tracks.</p>
	</div>

app/views/static_pages/home.html.erb
 <% if !current_user %>
<div class="row welcome">
  <div class="span12">
    <div class="well">
     
      <h1>Welcome to Collaborave</h1>
      <h3>An online mixer and recording application for music collaboration</h3>
      <div style="width:100%;display:inline-block;">
      <h4><%= link_to("Sign up", signup_url) %>, <%= link_to("Sign in", signin_url) %> or 
        <form action="/sessions" method="POST" style="display: inline-block;">
          <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
          <input type="hidden" name="session[email]" value="guest@collaborave.com">
          <input type="hidden" name="session[password]" value="foobies">
          <div class="form-group">
          <input class="btn btn-large btn-primary" type="submit" value="Sign in as a Guest">
        </div>
        </form>
      </h4>
    </div>
    </div>
  </div>
</div>
<% else %>
<div id="content"></div>

<div id="download-overlay" class="progress-overlay">
  <div class="progress-container">
    <h2>Downloading Audio...</h2>
    <h2>This may take a while - sorry, we're using full-quality wav files</h2>
    <div class="progress">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 5%;">
        <span class="sr-only">&nbsp;</span>
      </div>
    </div>
  </div>
</div>

<div id="upload-overlay" class="progress-overlay">
  <div class="progress-container">
    <h2>Uploading Audio...</h2>
    <div class="progress">
      <div class="progress-bar progress-bar-success" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: 5%;">
        <span class="sr-only">&nbsp;</span>
      </div>
    </div>
  </div>
</div>



<div class="modal fade" id="myModal">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            <h4 class="modal-title">Upload New Region</h4>
          </div>
          <div class="modal-body">  
              <%= form_for @region, html: { multipart: true } do |f| %>
                <%= f.file_field :path %>
                <%= f.hidden_field :track_id, value: 2 %>
                <%= f.hidden_field :start_time, value: 0 %>
                <%= f.hidden_field :redirect_hash, value: "" %>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <%= f.submit "Upload", class: "btn btn-primary", id: "region-upload" %>
              <% end %>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->
    
<script>
	$(document).ready(function(){
	  Collaborave.initialize();
    Collaborave.Recorder.initAudio();
	});
</script>
  <% end %>